#!/bin/bash

# Copyright (c) 2025 lzlhero
# Licensed under the GNU General Public License v3.0 (GPL-3.0)

# display usage information
if [[ -z "$1" ]]; then
  echo "Usage: $(basename "$0") filename.m3u8 [filename.mp4]"
  exit 1
fi

if [[ ! -f "$1" ]]; then
  echo "Error: File \"$1\" not found."
  exit 1
fi

# set basename
if [[ -z "$2" ]]; then
  basename="${1%.*}"
else
  basename="$2"
fi
# trim dot
while [[ "${basename: -1}" == "." ]]; do
  basename="${basename%.}"
done
ext="$(echo "${basename: -4}" | tr '[:upper:]' '[:lower:]')"
if [[ "$ext" == ".mp4" ]]; then
  basename="${basename%.*}"
fi

# set input file and output file
input="$1"
output="${basename}.mp4"

# validate output file name
if [[ ! -f "$output" ]]; then
  touch "$output" >/dev/null 2>&1
  if [[ $? -eq 0 ]]; then
    rm -f "$output"
  else
    echo "Error: Invalid output file name or path in \"$output\""
    exit 1
  fi
fi

# check the fixm3u8 flag in the input file
grep -q "# rebuilder: fixm3u8" "$input"
if [ $? -eq 1 ]; then
  # generate ffmpeg scan log
  scanlog="${basename}.ffmpeg.scan.log"
  echo "Generating \"$scanlog\" for advertisement removal..."
  ffmpeg -allowed_extensions ALL -protocol_whitelist "file,crypto,data" -i "$input" -c copy -f null /dev/null >"$scanlog" 2>&1
  if [[ $? -ne 0 ]]; then
    echo "Error: Generating \"$scanlog\" file errors."
    exit 1
  fi

  # rebuild m3u8 to remove ads
  node "$(dirname "$0")/js/fixm3u8.js" "$input" "$scanlog"
  if [ $? -ne 0 ]; then
    exit 1
  fi
fi

# merge all ts files to mp4 file
mergelog="${basename}.ffmpeg.merge.log"
echo
echo "Merging \"$output\" based on \"$input\"..."
ffmpeg -y -allowed_extensions ALL -protocol_whitelist "file,crypto,data" -i "$input" -c copy "$output" >"$mergelog" 2>&1
if [[ $? -eq 0 ]]; then
  echo "Successfully merged \"$output\"."
else
  echo "Error: Failed to merge \"$output\"."
  exit 1
fi
