#!/bin/bash

# Copyright (c) 2025 lzlhero
# Licensed under the GNU General Public License v3.0 (GPL-3.0)

if [ -z "$1" ]; then
  echo "Usage: $(basename "$0") bytes-length files"
  echo "Note: The files argument supports file wildcards."
  exit 1
fi

if [ -z "$2" ]; then
  echo "Error: missing files."
  exit 1
fi

for F in "${@:2}"; do
  [ -f "$F" ] || continue
  echo "$(basename "$F")"
  dd if="$F" of="${F%.*}.tmp" bs="$1" skip=1 > /dev/null 2>&1
  #tail -c +$(($1+1)) "$F" > "${F%.*}.tmp"
  mv -f "${F%.*}.tmp" "$F" >/dev/null 2>&1
done
